/*
Copyright (C) 1994-1995 Apogee Software, Ltd.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

// Registered
typedef enum
{

//  MENU SOUNDS
    D_MENUFLIP,
    D_ESCPRESSEDSND,
    D_MOVECURSORSND,
    D_SELECTSND,
    D_WARNINGBOXSND,
    D_INFOBOXSND,
    D_QUESTIONBOXSND,
    D_NOPESND,
    D_QUIT1SND,
    D_QUIT2SND,
    D_QUIT3SND,
    D_QUIT4SND,
    D_QUIT5SND,
    D_QUIT6SND,
    D_QUIT7SND,

//  GAME SOUNDS
    D_LEVELSTARTSND,
    D_LEVELDONESND,
    D_GAMEOVERSND,

//  LEVEL END SCREEN
    D_ENDBONUS1SND,
    D_NOBONUSSND,
    D_PERCENT100SND,

//  PLAYER SOUNDS
    D_HITWALLSND,
    D_SELECTWPNSND,
    D_NOWAYSND,
    D_DONOTHINGSND,
    //D_NOITEMSND,
    D_PLAYERDYINGSND,
    D_PLAYERTBDEATHSND,
    D_PLAYERTCDEATHSND,
    D_PLAYERLNDEATHSND,
    D_PLAYERDWDEATHSND,
    D_PLAYERIPFDEATHSND,
    D_PLAYERTBHURTSND,
    D_PLAYERTCHURTSND,
    D_PLAYERLNHURTSND,
    D_PLAYERDWHURTSND,
    D_PLAYERIPFHURTSND,
    D_PLAYERTBSND,
    D_PLAYERTCSND,
    D_PLAYERLNSND,
    D_PLAYERDWSND,
    D_PLAYERIPFSND,
    //D_WALK1SND,
    //D_WALK2SND,
    D_PLAYERBURNEDSND,
    D_PLAYERLANDSND,
    D_PLAYERCOUGHMSND,
    D_PLAYERCOUGHFSND,
    D_NETWIGGLESND,
    D_NETFALLSND,

//  PLAYER WEAPONS
    D_ATKPISTOLSND,
    D_ATKTWOPISTOLSND,
    D_ATKMP40SND,
    D_RICOCHET1SND,
    D_RICOCHET2SND,
    D_RICOCHET3SND,
    D_BAZOOKAFIRESND,
    D_FIREBOMBFIRESND,
    D_HEATSEEKFIRESND,
    D_DRUNKFIRESND,
    D_FLAMEWALLFIRESND,
    D_FLAMEWALLSND,
    D_SPLITFIRESND,
    D_SPLITSND,
    D_GRAVBUILDSND,
    D_GRAVFIRESND,
    D_GRAVSND,
    D_GRAVHITSND,
    D_FIREHITSND,
    D_MISSILEFLYSND,
    D_MISSILEHITSND,
    D_EXCALIBOUNCESND,
    D_EXCALISWINGSND,
    D_EXCALIHITSND,
    D_EXCALIBUILDSND,
    D_EXCALIBLASTSND,
    D_GODMODEFIRESND,
    D_GODMODE1SND,
    D_GODMODE2SND,
    D_GODMODE3SND,
    D_LOSEMODESND,
    D_DOGMODEPANTSND,
    D_DOGMODEBITE1SND,
    D_DOGMODEBITE2SND,
    D_DOGMODELICKSND,
    D_DOGMODEBLASTSND,
    D_DOGMODEPREPBLASTSND,
    D_DOGMANSND,
    D_DOGWOMANSND,
    D_GODMANSND,
    D_GODWOMANSND,
    D_FLYINGSND,

//  PLAYER-CAUSED SOUNDS
    D_GLASSBREAKSND,
    D_ITEMBLOWSND,
    D_BONUSBARRELSND,
    D_TOUCHPLATESND,
    D_BADTOUCHSND,
    D_EXPLODEFLOORSND,
    D_EXPLODESND,
    //D_GASSTARTSND,
    D_GASHISSSND,
    D_GASENDSND,
    D_GASMASKSND,

//  GET ITEM SOUNDS
    D_GETKEYSND,
    D_GETBONUSSND,
    D_GETHEALTH1SND,
    D_GETHEALTH2SND,
    D_COOKHEALTHSND,
    D_GETWEAPONSND,
    D_GETKNIFESND,
    D_GETGODSND,
    D_GETDOGSND,
    D_GETFLEETSND,
    D_GETELASTSND,
    D_GETSHROOMSSND,
    D_GETBVESTSND,
    D_GETAVESTSND,
    D_GETMASKSND,
    D_GETBATSND,
    D_GETHEADSND,
    D_GET1UPSND,
    D_GET3UPSND,
    D_RESPAWNSND,
    D_PLAYERSPAWNSND,

//  ACTOR SOUNDS
    D_LOWGUARD1SEESND,
    D_LOWGUARD1ASEESND,
    D_LOWGUARD1SEE2SND,
    //D_LOWGUARD2SEESND,
    //D_LOWGUARD2ASEESND,
    //D_LOWGUARD2SEE2SND,
    D_LOWGUARDOUCHSND,
    D_LOWGUARD1DIESND,
    //D_LOWGUARD2DIESND,
    D_SNEAKYSPRINGMSND,
    //D_SNEAKYSPRINGFSND,

    D_HIGHGUARD1SEESND,
    D_HIGHGUARD2SEESND,
    D_HIGHGUARDOUCHSND,
    D_HIGHGUARDDIESND,

    D_OVERP1SEESND,
    //D_OVERP2SEESND,
    D_OVERPNETSND,
    D_OVERPOUCHSND,
    D_OVERPDIESND,

    D_STRIKE1SEESND,
    //D_STRIKE2SEESND,
    D_STRIKEROLLSND,
    D_STRIKEOUCHSND,
    D_STRIKEDIESND,

    D_BLITZ1SEESND,
    D_BLITZ2SEESND,
    D_BLITZSTEALSND,
    D_BLITZOUCHSND,
    D_BLITZDIESND,
    D_BLITZPLEADSND,
    D_BLITZPLEAD1SND,
    D_BLITZPLEAD2SND,

    D_ENFORCERSEESND,
    D_ENFORCERFIRESND,
    D_ENFORCERTHROWSND,
    D_ENFORCEROUCHSND,
    D_ENFORCERDIESND,

    D_MONKSEESND,
    D_MONKGRABSND,
    D_MONKOUCHSND,
    D_MONKDIESND,

    D_FIREMONKSEESND,
    D_FIREMONKFIRESND,
    D_FIREMONKOUCHSND,
    D_FIREMONKDIESND,

    D_ROBOTSEESND,
    D_ROBOTFIRESND,
    D_ROBOTDIESND,

    D_DARIANSEESND,
    D_DARIANGONNAUSESND,
    D_DARIANHIDESND,
    D_DARIANDIESND,
    D_DARIANSAY1,
    D_DARIANSAY2,
    D_DARIANSAY3,

    D_KRISTSEESND,
    D_KRISTMOTORSND,
    D_KRISTTURNSND,
    D_KRISTDROPSND,
    D_KRISTMINEBEEPSND,
    D_KRISTMINEHITSND,
    D_KRISTDIESND,
    D_KRISTSAY1,
    D_KRISTSAY2,
    D_KRISTSAY3,

    D_NMESEESND,
    D_NMEREADYSND,
    D_NMEAPARTSND,
    D_NMEUFOSND,

    D_DARKMONKSEESND,
    D_DARKMONKFIRE1SND,
    D_DARKMONKFIRE2SND,
    D_DARKMONKFIRE3SND,
    D_DARKMONKFIRE4SND,
    D_DARKMONKRECHARGESND,
    D_DARKMONKFLOATSND,
    D_DARKMONKDIESND,
    D_DARKMONKSAY1,
    D_DARKMONKSAY2,
    D_DARKMONKSAY3,

    D_SNAKESEESND,
    D_SNAKEREADYSND,
    D_SNAKECHARGESND,
    D_SNAKEOUCHSND,
    D_SNAKEDIESND,
    D_SNAKESPITSND,
    D_SNAKESAY1,
    D_SNAKESAY2,
    D_SNAKESAY3,

    D_EMPLACEMENTSEESND,
    D_EMPLACEMENTFIRESND,
    D_BIGEMPLACEFIRESND,

//  ENVIRONMENT SOUNDS
    D_OPENDOORSND,
    D_CLOSEDOORSND,
    D_DOORHITSND,
    D_FIRECHUTESND,
    D_FIREBALLSND,
    D_FIREBALLHITSND,
    D_BLADESPINSND,
    D_PUSHWALLSND,
    D_PUSHWALLHITSND,
    D_GOWALLSND,
    D_TURBOWALLSND,
    D_BOULDERHITSND,
    D_BOULDERROLLSND,
    D_PITTRAPSND,
    D_FIREJETSND,
    D_ACTORSQUISHSND,
    D_ACTORBURNEDSND,
    D_ACTORSKELETONSND,
    D_SPEARSTABSND,
    D_CYLINDERMOVESND,
    D_ELEVATORONSND,
    D_ELEVATORENDSND,
    D_SPRINGBOARDSND,
    D_LIGHTNINGSND,
    D_WINDSND,
    //D_WATERSND,

//  SECRET SOUNDS
    D_DOPEFISHSND,
    D_YOUSUCKSND,
    D_SILLYMOVESND,
    D_SOUNDSELECTSND,
    D_SOUNDESCSND,
    D_BODYLANDSND,
    D_GIBSPLASHSND,
    D_ACTORLANDSND,

    D_LASTSOUND = -1

} digisounds;

// Shareware
typedef enum
{
// MENU SOUNDS
    D_SW_MENUFLIP,
    D_SW_ESCPRESSEDSND,
    D_SW_MOVECURSORSND,
    D_SW_SELECTSND,
    D_SW_WARNINGBOXSND,
    D_SW_INFOBOXSND,
    D_SW_QUESTIONBOXSND,
    D_SW_NOPESND,

// GAME SOUNDS
    D_SW_LEVELSTARTSND,
    D_SW_LEVELDONESND,
    D_SW_GAMEOVERSND,

// LEVEL END SCREEN
    D_SW_ENDBONUS1SND,

// PLAYER SOUNDS
    D_SW_HITWALLSND,
    D_SW_SELECTWPNSND,
    D_SW_NOWAYSND,
    D_SW_DONOTHINGSND,
    //D_SW_NOITEMSND,
    D_SW_PLAYERDYINGSND,
    D_SW_PLAYERTCDEATHSND,
    D_SW_PLAYERTCHURTSND,
    D_SW_PLAYERTCSND,
    //D_SW_WALK1SND,
    //D_SW_WALK2SND,
    D_SW_PLAYERBURNEDSND,
    D_SW_PLAYERLANDSND,
    D_SW_PLAYERCOUGHMSND,

// PLAYER WEAPONS
    D_SW_ATKPISTOLSND,
    D_SW_ATKTWOPISTOLSND,
    D_SW_ATKMP40SND,
    D_SW_RICOCHET1SND,
    D_SW_RICOCHET2SND,
    D_SW_RICOCHET3SND,
    D_SW_BAZOOKAFIRESND,
    D_SW_HEATSEEKFIRESND,
    D_SW_FIREBOMBFIRESND,
    D_SW_DRUNKFIRESND,
    D_SW_FLAMEWALLFIRESND,
    D_SW_FLAMEWALLSND,
    D_SW_GRAVSND,
    D_SW_FIREHITSND,
    D_SW_MISSILEFLYSND,
    D_SW_MISSILEHITSND,
    D_SW_GODMODEFIRESND,
    D_SW_GODMODE1SND,
    D_SW_GODMODE2SND,
    D_SW_GODMODE3SND,
    D_SW_LOSEMODESND,
    D_SW_GODMANSND,
    D_SW_FLYINGSND,

// PLAYER-CAUSED SOUNDS
    D_SW_GLASSBREAKSND,
    D_SW_ITEMBLOWSND,
    D_SW_BONUSBARRELSND,
    D_SW_TOUCHPLATESND,
    D_SW_BADTOUCHSND,
    D_SW_EXPLODEFLOORSND,
    D_SW_EXPLODESND,
    //D_SW_GASSTARTSND,
    D_SW_GASHISSSND,
    D_SW_GASENDSND,
    D_SW_GASMASKSND,

// GET ITEM SOUNDS
    D_SW_GETKEYSND,
    D_SW_GETBONUSSND,
    D_SW_GETHEALTH1SND,
    D_SW_COOKHEALTHSND,
    D_SW_GETWEAPONSND,
    D_SW_GETGODSND,
    D_SW_GETFLEETSND,
    D_SW_GETELASTSND,
    D_SW_GETSHROOMSSND,
    D_SW_GETBVESTSND,
    D_SW_GETAVESTSND,
    D_SW_GETMASKSND,
    D_SW_GET1UPSND,
    D_SW_RESPAWNSND,
    D_SW_PLAYERSPAWNSND,

// ACTOR SOUNDS
    D_SW_LOWGUARD1SEESND,
    D_SW_LOWGUARD1SEE2SND,
    D_SW_LOWGUARDOUCHSND,
    D_SW_LOWGUARD1DIESND,
    D_SW_SNEAKYSPRINGMSND,

    D_SW_HIGHGUARD1SEESND,
    D_SW_HIGHGUARDOUCHSND,
    D_SW_HIGHGUARDDIESND,

    D_SW_STRIKE1SEESND,
    D_SW_STRIKEROLLSND,
    D_SW_STRIKEOUCHSND,
    D_SW_STRIKEDIESND,

    D_SW_BLITZ1SEESND,
    D_SW_BLITZSTEALSND,
    D_SW_BLITZOUCHSND,
    D_SW_BLITZDIESND,
    D_SW_BLITZPLEADSND,
    D_SW_BLITZPLEAD1SND,
    D_SW_BLITZPLEAD2SND,

    D_SW_ENFORCERSEESND,
    D_SW_ENFORCERFIRESND,
    D_SW_ENFORCERTHROWSND,
    D_SW_ENFORCEROUCHSND,
    D_SW_ENFORCERDIESND,

    D_SW_ROBOTSEESND,
    D_SW_ROBOTFIRESND,
    D_SW_ROBOTDIESND,

    D_SW_KRISTMOTORSND,

// ENVIRONMENT SOUNDS
    D_SW_OPENDOORSND,
    D_SW_CLOSEDOORSND,
    D_SW_DOORHITSND,
    D_SW_FIRECHUTESND,
    D_SW_FIREBALLSND,
    D_SW_FIREBALLHITSND,
    D_SW_BLADESPINSND,
    D_SW_PUSHWALLSND,
    D_SW_PUSHWALLHITSND,
    D_SW_GOWALLSND,
    D_SW_TURBOWALLSND,
    D_SW_PITTRAPSND,
    D_SW_FIREJETSND,
    D_SW_ACTORSQUISHSND,
    D_SW_ACTORBURNEDSND,
    D_SW_ACTORSKELETONSND,
    D_SW_SPEARSTABSND,
    D_SW_CYLINDERMOVESND,
    D_SW_ELEVATORONSND,
    D_SW_ELEVATORENDSND,
    D_SW_SPRINGBOARDSND,
    D_SW_LIGHTNINGSND,
    //D_SW_WINDSND,

// SECRET SOUNDS
    D_SW_YOUSUCKSND,
    D_SW_BODYLANDSND,
    D_SW_GIBSPLASHSND,
    D_SW_ACTORLANDSND
} digisounds_sw;

static sound_t sounds[MAXSOUNDS] =
{
//SD_MENUFLIP,
    {{D_MENUFLIP, D_SW_MENUFLIP, MUSE_MENUFLIPSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_ESCPRESSEDSND,
    {{D_ESCPRESSEDSND, D_SW_ESCPRESSEDSND, MUSE_ESCPRESSEDSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_MOVECURSORSND,
    {{D_MOVECURSORSND, D_SW_MOVECURSORSND, MUSE_MOVECURSORSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_SELECTSND,
    {{D_SELECTSND, D_SW_SELECTSND, MUSE_SELECTSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_WARNINGBOXSND,
    {{D_WARNINGBOXSND, D_SW_WARNINGBOXSND, MUSE_WARNINGBOXSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_INFOBOXSND,
    {{D_INFOBOXSND, D_SW_INFOBOXSND, MUSE_INFOBOXSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_QUESTIONBOXSND,
    {{D_QUESTIONBOXSND, D_SW_QUESTIONBOXSND, MUSE_QUESTIONBOXSND}, 0, SD_PRIOMENU, 0, 0, 0},

//SD_NOPESND,
    {{D_NOPESND, D_SW_NOPESND, MUSE_NOPESND,          },  0, SD_PRIOMENU, 0, 0, 0},

//SD_QUIT1SND,
    {{D_QUIT1SND, D_LASTSOUND , MUSE_SELECTSND,        },  0, SD_PRIOQUIT, 0, 0, 0},

//SD_QUIT2SND,
    {{D_QUIT2SND, D_LASTSOUND, MUSE_SELECTSND,        },  0,SD_PRIOQUIT, 0, 0, 0},

//SD_QUIT3SND,
    {{D_QUIT3SND, D_LASTSOUND, MUSE_SELECTSND,        },  0,SD_PRIOQUIT, 0, 0, 0},

//SD_QUIT4SND,
    {{D_QUIT4SND, D_LASTSOUND, MUSE_SELECTSND,        },  0,SD_PRIOQUIT, 0, 0, 0},

//SD_QUIT5SND,
    {{D_QUIT5SND, D_LASTSOUND, MUSE_SELECTSND,        },  0,SD_PRIOQUIT, 0, 0, 0},

//SD_QUIT6SND,
    {{D_QUIT6SND, D_LASTSOUND, MUSE_SELECTSND,        },  0,SD_PRIOQUIT, 0, 0, 0},

//SD_QUIT7SND,
    {{D_QUIT7SND, D_LASTSOUND, MUSE_SELECTSND,        },  0,SD_PRIOQUIT, 0, 0, 0},

//SD_LEVELSTARTSND,
    {{D_LEVELSTARTSND, D_SW_LEVELSTARTSND, MUSE_LEVELSTARTSND,    },  0,SD_PRIOGAME, 0, 0, 0},

//SD_LEVELDONESND,
    {{D_LEVELDONESND, D_SW_LEVELDONESND, MUSE_LEVELENDSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GAMEOVERSND,
    {{D_GAMEOVERSND, D_SW_GAMEOVERSND, MUSE_GAMEOVERSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_ENDBONUS1SND,
    {{D_ENDBONUS1SND, D_SW_ENDBONUS1SND, MUSE_ENDBONUS1SND,     },  SD_PITCHSHIFTOFF,SD_PRIOGAME, 0, 0, 0},

//SD_NOBONUSSND,
    {{D_NOBONUSSND, D_LASTSOUND, MUSE_NOBONUSSND,       },  0,SD_PRIOGAME, 0, 0, 0},

//SD_PERCENT100SND,
    {{D_PERCENT100SND, D_LASTSOUND, MUSE_PERCENT100SND,    },  0,SD_PRIOGAME, 0, 0, 0},

//SD_HITWALLSND,
    {{D_HITWALLSND, D_SW_HITWALLSND, MUSE_HITWALLSND,       },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_SELECTWPNSND,
    {{D_SELECTWPNSND, D_SW_SELECTWPNSND, MUSE_SELECTWPNSND,     },  0,SD_PRIOGAME, 0, 0, 0},

//SD_NOWAYSND,
    {{D_NOWAYSND, D_SW_NOWAYSND, MUSE_NOWAYSND,         },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_DONOTHINGSND,
    {{D_DONOTHINGSND, D_SW_DONOTHINGSND, MUSE_DONOTHINGSND,     },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_NOITEMSND,
    {{D_NOWAYSND, D_SW_NOWAYSND, MUSE_NOITEMSND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_PLAYERDYINGSND,
    {{D_PLAYERDYINGSND, D_SW_PLAYERDYINGSND, MUSE_PLAYERDYINGSND,   },  SD_PITCHSHIFTOFF,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERTCDEATHSND,
    {{D_PLAYERTCDEATHSND, D_SW_PLAYERTCDEATHSND, MUSE_PLAYERDEATHSND,   },  0,SD_PRIOGAME, 0, 0, 0},

//SD_PLAYERTBDEATHSND,
    {{D_PLAYERTBDEATHSND, D_SW_PLAYERTCDEATHSND, MUSE_PLAYERDEATHSND,   },  0,SD_PRIOGAME, 0, 0, 0},

//SD_PLAYERDWDEATHSND,
    {{D_PLAYERDWDEATHSND, D_SW_PLAYERTCDEATHSND, MUSE_PLAYERDEATHSND,   },  0,SD_PRIOGAME, 0, 0, 0},

//SD_PLAYERLNDEATHSND,
    {{D_PLAYERLNDEATHSND, D_SW_PLAYERTCDEATHSND, MUSE_PLAYERDEATHSND,   },  0,SD_PRIOGAME, 0, 0, 0},

//SD_PLAYERIPFDEATHSND,
    {{D_PLAYERIPFDEATHSND, D_SW_PLAYERTCDEATHSND, MUSE_PLAYERDEATHSND,   },  0,SD_PRIOGAME, 0, 0, 0},

//SD_PLAYERTCHURTSND,
    {{D_PLAYERTCHURTSND, D_SW_PLAYERTCHURTSND, MUSE_PLAYERHURTSND,    },  SD_PLAYONCE, SD_PRIOPHURT, 0, 0, 0},

//SD_PLAYERTBHURTSND,
    {{D_PLAYERTBHURTSND, D_SW_PLAYERTCHURTSND, MUSE_PLAYERHURTSND,    },  SD_PLAYONCE, SD_PRIOPHURT, 0, 0, 0},

//SD_PLAYERDWHURTSND,
    {{D_PLAYERDWHURTSND, D_SW_PLAYERTCHURTSND, MUSE_PLAYERHURTSND,    },  SD_PLAYONCE, SD_PRIOPHURT, 0, 0, 0},

//SD_PLAYERLNHURTSND,
    {{D_PLAYERLNHURTSND, D_SW_PLAYERTCHURTSND, MUSE_PLAYERHURTSND,    },  SD_PLAYONCE, SD_PRIOPHURT, 0, 0, 0},

//SD_PLAYERIPFHURTSND,
    {{D_PLAYERIPFHURTSND, D_SW_PLAYERTCHURTSND, MUSE_PLAYERHURTSND,    },  SD_PLAYONCE, SD_PRIOPHURT, 0, 0, 0},

//SD_PLAYERTCSND,
    {{D_PLAYERTCSND, D_SW_PLAYERTCSND, MUSE_PLAYERYESSND,     },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERTBSND,
    {{D_PLAYERTBSND, D_SW_PLAYERTCSND, MUSE_PLAYERYESSND,     },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERDWSND,
    {{D_PLAYERDWSND, D_SW_PLAYERTCSND, MUSE_PLAYERYESSND,     },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERLNSND,
    {{D_PLAYERLNSND, D_SW_PLAYERTCSND, MUSE_PLAYERYESSND,     },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERIPFSND,
    {{D_PLAYERIPFSND, D_SW_PLAYERTCSND, MUSE_PLAYERYESSND,     },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_WALK1SND,
// {{D_WALK1SND,            MUSE_WALK1SND,       },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_WALK2SND,
// {{D_WALK2SND,            MUSE_WALK2SND,       },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERBURNEDSND,
    {{D_PLAYERBURNEDSND, D_SW_PLAYERBURNEDSND, MUSE_PLAYERHURTSND,    },  SD_PLAYONCE,SD_PRIOPHURT, 0, 0, 0},

//SD_PLAYERLANDSND,
    {{D_PLAYERLANDSND, D_SW_PLAYERLANDSND, MUSE_PLAYERLANDSND,    },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERCOUGHMSND,
    {{D_PLAYERCOUGHMSND, D_SW_PLAYERCOUGHMSND, MUSE_LASTSOUND,        },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_PLAYERCOUGHFSND,
    {{D_PLAYERCOUGHFSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_NETWIGGLESND,
    {{D_NETWIGGLESND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_NETFALLSND,
    {{D_NETFALLSND, D_LASTSOUND, MUSE_NETFALLSND,       },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_ATKPISTOLSND,
    {{D_ATKPISTOLSND, D_SW_ATKPISTOLSND, MUSE_ATKPISTOLSND,     },  SD_WRITE,SD_PRIOPGUNS, 0, 0, 0},

//SD_ATKTWOPISTOLSND,
    {{D_ATKTWOPISTOLSND, D_SW_ATKTWOPISTOLSND, MUSE_ATKPISTOLSND,     },  SD_WRITE,SD_PRIOPGUNS, 0, 0, 0},

//SD_ATKMP40SND,

    {{D_ATKMP40SND, D_SW_ATKMP40SND, MUSE_ATKMP40SND,       },  SD_WRITE,SD_PRIOPMP40, 0, 0, 0},

//SD_RICOCHET1SND,

    {{D_RICOCHET1SND, D_SW_RICOCHET1SND, MUSE_RICOCHETSND,      },  SD_WRITE,SD_PRIOPCAUSD, 0, 0, 0},

//SD_RICOCHET2SND,

    {{D_RICOCHET2SND, D_SW_RICOCHET2SND, MUSE_RICOCHETSND,      },  SD_WRITE,SD_PRIOPCAUSD, 0, 0, 0},

//SD_RICOCHET3SND,

    {{D_RICOCHET3SND, D_SW_RICOCHET3SND, MUSE_RICOCHETSND,      },  SD_WRITE,SD_PRIOPCAUSD, 0, 0, 0},

//SD_BAZOOKAFIRESND,

    {{D_BAZOOKAFIRESND, D_SW_BAZOOKAFIRESND, MUSE_MISSILEFIRESND,   },  SD_WRITE,SD_PRIOPMISS, 0, 0, 0},

//SD_FIREBOMBFIRESND,

    {{D_FIREBOMBFIRESND, D_SW_FIREBOMBFIRESND, MUSE_MISSILEFIRESND,   },  SD_WRITE,SD_PRIOPMISS, 0, 0, 0},

//SD_HEATSEEKFIRESND,

    {{D_HEATSEEKFIRESND, D_SW_HEATSEEKFIRESND, MUSE_MISSILEFIRESND,   },  SD_WRITE,SD_PRIOPMISS, 0, 0, 0},

//SD_DRUNKFIRESND,

    {{D_DRUNKFIRESND, D_SW_DRUNKFIRESND, MUSE_MISSILEFIRESND,   },  SD_WRITE,SD_PRIOPMISS, 0, 0, 0},

//SD_FLAMEWALLFIRESND,

    {{D_FLAMEWALLFIRESND, D_SW_FLAMEWALLFIRESND, MUSE_MISSILEFIRESND,   },  SD_WRITE,SD_PRIOPMISS, 0, 0, 0},

//SD_FLAMEWALLSND,

    {{D_FLAMEWALLSND, D_SW_FLAMEWALLSND, MUSE_FLAMEWALLSND,     },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_SPLITFIRESND,

    {{D_SPLITFIRESND, D_LASTSOUND, MUSE_MISSILEFIRESND,   },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_SPLITSND,

    {{D_SPLITSND, D_LASTSOUND, MUSE_MISSILEFIRESND,   },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_GRAVBUILDSND,

    {{D_GRAVBUILDSND, D_LASTSOUND, MUSE_WEAPONBUILDSND,   },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_GRAVFIRESND,

    {{D_GRAVFIRESND, D_LASTSOUND, MUSE_ENERGYFIRESND,    },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_GRAVSND,

    {{D_GRAVSND, D_SW_GRAVSND, MUSE_LASTSOUND,        },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_GRAVHITSND,

    {{D_GRAVHITSND, D_LASTSOUND, MUSE_MISSILEHITSND,    },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_FIREHITSND,

    {{D_FIREHITSND, D_SW_FIREHITSND, MUSE_MISSILEHITSND,    },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_MISSILEFLYSND,

    {{D_MISSILEFLYSND, D_SW_MISSILEFLYSND, MUSE_LASTSOUND,        },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_MISSILEHITSND,

    {{D_MISSILEHITSND, D_SW_MISSILEHITSND, MUSE_MISSILEHITSND,    },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_EXCALIBOUNCESND,

    {{D_EXCALIBOUNCESND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_EXCALISWINGSND,

    {{D_EXCALISWINGSND, D_LASTSOUND, MUSE_MISSILEFIRESND,   },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_EXCALIHITSND,

    {{D_EXCALIHITSND, D_LASTSOUND, MUSE_MISSILEHITSND,    },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_EXCALIBUILDSND,

    {{D_EXCALIBUILDSND, D_LASTSOUND, MUSE_WEAPONBUILDSND,   },  0,SD_PRIOPSNDS, 0, 0, 0},

//SD_EXCALIBLASTSND,

    {{D_EXCALIBLASTSND, D_LASTSOUND, MUSE_ENERGYFIRESND,    },  0,SD_PRIOPMISS, 0, 0, 0},

//SD_GODMODEFIRESND,

    {{D_GODMODEFIRESND, D_SW_GODMODEFIRESND, MUSE_ENERGYFIRESND,    },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GODMODE1SND,

    {{D_GODMODE1SND, D_SW_GODMODE1SND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GODMODE2SND,

    {{D_GODMODE2SND, D_SW_GODMODE2SND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GODMODE3SND,

    {{D_GODMODE3SND, D_SW_GODMODE3SND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_LOSEMODESND,

    {{D_LOSEMODESND, D_SW_LOSEMODESND, MUSE_LOSEMODESND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_DOGMODEPANTSND,

    {{D_DOGMODEPANTSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGMODEBITE1SND,

    {{D_DOGMODEBITE1SND, D_LASTSOUND, MUSE_DOGBITESND,      },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGMODEBITE2SND,

    {{D_DOGMODEBITE2SND, D_LASTSOUND, MUSE_DOGBITESND,      },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGMODELICKSND,

    {{D_DOGMODELICKSND, D_LASTSOUND, MUSE_DOGLICKSND,       },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGMODEBLASTSND,

    {{D_DOGMODEBLASTSND, D_LASTSOUND, MUSE_DOGBITESND,      },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGMODEPREPBLASTSND,

    {{D_DOGMODEPREPBLASTSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGMANSND,

    {{D_DOGMANSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_DOGWOMANSND,

    {{D_DOGWOMANSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GODMANSND,

    {{D_GODMANSND, D_SW_GODMANSND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GODWOMANSND,

    {{D_GODWOMANSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_FLYINGSND,

    {{D_FLYINGSND, D_SW_FLYINGSND, MUSE_LASTSOUND,        },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GLASSBREAKSND,

    {{D_GLASSBREAKSND, D_SW_GLASSBREAKSND, MUSE_GLASSBREAKSND,    },  0,SD_PRIOGLASS, 0, 0, 0},

//SD_ITEMBLOWSND,

    {{D_ITEMBLOWSND, D_SW_ITEMBLOWSND, MUSE_EXPLOSIONSND,     },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_BONUSBARRELSND,

    {{D_BONUSBARRELSND, D_SW_BONUSBARRELSND, MUSE_EXPLOSIONSND,     },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_TOUCHPLATESND,

    {{D_TOUCHPLATESND, D_SW_TOUCHPLATESND, MUSE_TOUCHPLATESND,    },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_BADTOUCHSND,

    {{D_BADTOUCHSND, D_SW_BADTOUCHSND, MUSE_BADTOUCHSND,      },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_EXPLODEFLOORSND,

    {{D_EXPLODEFLOORSND, D_SW_EXPLODEFLOORSND, MUSE_EXPLOSIONSND,     },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_EXPLODESND,

    {{D_EXPLODESND, D_SW_EXPLODESND, MUSE_EXPLOSIONSND,     },  0,SD_PRIOEXPL, 0, 0, 0},

//SD_GASSTARTSND,

    {{D_TOUCHPLATESND, D_SW_TOUCHPLATESND, MUSE_SWITCHSND,      },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_GASHISSSND,

    {{D_GASHISSSND, D_SW_GASHISSSND, MUSE_LASTSOUND,        },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_GASENDSND,

    {{D_GASENDSND, D_SW_GASENDSND, MUSE_SWITCHSND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_GASMASKSND,

    {{D_GASMASKSND, D_SW_GASMASKSND, MUSE_LASTSOUND,        },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETKEYSND,

    {{D_GETKEYSND, D_SW_GETKEYSND, MUSE_GETKEYSND,        },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETBONUSSND,

    {{D_GETBONUSSND, D_SW_GETBONUSSND, MUSE_GETBONUSSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETHEALTH1SND,

    {{D_GETHEALTH1SND, D_SW_GETHEALTH1SND, MUSE_GETHEALTHSND,     },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETHEALTH2SND,

    {{D_GETHEALTH2SND, D_SW_GETHEALTH1SND, MUSE_GETHEALTHSND,     },  0,SD_PRIOGAME, 0, 0, 0},

//SD_COOKHEALTHSND,

    {{D_COOKHEALTHSND, D_SW_COOKHEALTHSND, MUSE_GETBONUSSND,      },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_GETWEAPONSND,

    {{D_GETWEAPONSND, D_SW_GETWEAPONSND, MUSE_GETWEAPONSND,     },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETKNIFESND,

    {{D_GETKNIFESND, D_LASTSOUND, MUSE_GETWEAPONSND,     },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETGODSND,

    {{D_GETGODSND, D_SW_GETGODSND, MUSE_GETPOWERUPSND,    },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GETDOGSND,

    {{D_GETDOGSND, D_LASTSOUND, MUSE_GETPOWERUPSND,    },  0,SD_PRIOGODDOG, 0, 0, 0},

//SD_GETFLEETSND,

    {{D_GETFLEETSND, D_SW_GETFLEETSND, MUSE_GETPOWERUPSND,    },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETELASTSND,

    {{D_GETELASTSND, D_SW_GETELASTSND, MUSE_GETPOWERDOWNSND,  },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETSHROOMSSND,

    {{D_GETSHROOMSSND, D_SW_GETSHROOMSSND, MUSE_GETPOWERDOWNSND,  },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETBVESTSND,

    {{D_GETBVESTSND, D_SW_GETBVESTSND, MUSE_GETARMORSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETAVESTSND,

    {{D_GETAVESTSND, D_SW_GETAVESTSND, MUSE_GETARMORSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETMASKSND,

    {{D_GETMASKSND, D_SW_GETMASKSND, MUSE_GETARMORSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETBATSND,

    {{D_GETBATSND, D_LASTSOUND, MUSE_GETWEIRDSND,      },  0,SD_PRIOGAME, 0, 0, 0},

//SD_GETHEADSND,

    {{D_GETHEADSND, D_LASTSOUND, MUSE_GETWEIRDSND,      },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_GET1UPSND,

    {{D_GET1UPSND, D_SW_GET1UPSND, MUSE_GETLIFESND,       },   SD_PITCHSHIFTOFF,SD_PRIOGAME, 0, 0, 0},

//SD_GET3UPSND,

    {{D_GET3UPSND, D_LASTSOUND, MUSE_GETLIFESND,       },   SD_PITCHSHIFTOFF,SD_PRIOGAME, 0, 0, 0},

//SD_RESPAWNSND,

    {{D_RESPAWNSND, D_SW_RESPAWNSND, MUSE_GETBONUSSND,      },   SD_PITCHSHIFTOFF,SD_PRIOGAME, 0, 0, 0},

//SD_PLAYERSPAWNSND,

    {{D_PLAYERSPAWNSND, D_SW_PLAYERSPAWNSND, MUSE_GETLIFESND,       },   SD_PITCHSHIFTOFF,SD_PRIOGAME, 0, 0, 0},

//SD_LOWGUARD1SEESND,

    {{D_LOWGUARD1SEESND, D_SW_LOWGUARD1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_LOWGUARD1ASEESND,

    {{D_LOWGUARD1ASEESND, D_SW_LOWGUARD1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_LOWGUARD1SEE3SND,

    {{D_LOWGUARD1SEE2SND, D_SW_LOWGUARD1SEE2SND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_LOWGUARD2SEESND,

    {{D_LOWGUARD1SEESND, D_SW_LOWGUARD1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_LOWGUARD2ASEESND,

    {{D_LOWGUARD1ASEESND, D_SW_LOWGUARD1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_LOWGUARD2SEE3SND,

    {{D_LOWGUARD1SEE2SND, D_SW_LOWGUARD1SEE2SND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_LOWGUARDFIRESND,

    {{D_ATKPISTOLSND, D_SW_ATKPISTOLSND, MUSE_ACTORFIRESND,        },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_LOWGUARDOUCHSND,

    {{D_LOWGUARDOUCHSND, D_SW_LOWGUARDOUCHSND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_LOWGUARD1DIESND,

    {{D_LOWGUARD1DIESND, D_SW_LOWGUARD1DIESND, MUSE_ACTORDIESND,       },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_LOWGUARD2DIESND,

    {{D_LOWGUARD1DIESND, D_SW_LOWGUARD1DIESND, MUSE_ACTORDIESND,       },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_SNEAKYSPRINGMSND,

    {{D_SNEAKYSPRINGMSND, D_SW_SNEAKYSPRINGMSND, MUSE_ACTORDOITSND,     },  0,SD_PRIOASNEAK, 0, 0, 0},

//SD_SNEAKYSPRINGFSND,

    {{D_SNEAKYSPRINGMSND, D_SW_SNEAKYSPRINGMSND, MUSE_ACTORDOITSND,     },  0,SD_PRIOASNEAK, 0, 0, 0},

//SD_HIGHGUARD1SEESND,

    {{D_HIGHGUARD1SEESND, D_SW_HIGHGUARD1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_HIGHGUARD2SEESND,

    {{D_HIGHGUARD2SEESND, D_SW_HIGHGUARD1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_HIGHGUARDFIRESND,

    {{D_ATKMP40SND, D_SW_ATKMP40SND, MUSE_ACTORFIRESND,     },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_HIGHGUARDOUCHSND,

    {{D_HIGHGUARDOUCHSND, D_SW_HIGHGUARDOUCHSND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_HIGHGUARDDIESND,

    {{D_HIGHGUARDDIESND, D_SW_HIGHGUARDDIESND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_OVERP1SEESND,

    {{D_OVERP1SEESND, D_LASTSOUND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_OVERP2SEESND,

    {{D_OVERP1SEESND, D_LASTSOUND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_OVERPFIRESND,

    {{D_ATKPISTOLSND, D_SW_ATKPISTOLSND, MUSE_ACTORFIRESND,        },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_OVERPNETSND,

    {{D_OVERPNETSND, D_LASTSOUND, MUSE_ACTORTHROWSND,    },  0,SD_PRIOASNEAK, 0, 0, 0},

//SD_OVERPOUCHSND,

    {{D_OVERPOUCHSND, D_LASTSOUND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_OVERPDIESND,

    {{D_OVERPDIESND, D_LASTSOUND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_STRIKE1SEESND,

    {{D_STRIKE1SEESND, D_SW_STRIKE1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_STRIKE2SEESND,

    {{D_STRIKE1SEESND, D_SW_STRIKE1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_STRIKEFIRESND,

    {{D_ATKPISTOLSND, D_SW_ATKPISTOLSND, MUSE_ACTORFIRESND,        },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_STRIKEROLLSND,

    {{D_STRIKEROLLSND, D_SW_STRIKEROLLSND, MUSE_ACTORROLLSND,     },  0,SD_PRIOASNEAK, 0, 0, 0},

//SD_STRIKEOUCHSND,

    {{D_STRIKEOUCHSND, D_SW_STRIKEOUCHSND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_STRIKEDIESND,

    {{D_STRIKEDIESND, D_SW_STRIKEDIESND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_BLITZ1SEESND,

    {{D_BLITZ1SEESND, D_SW_BLITZ1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_BLITZ2SEESND,

    {{D_BLITZ2SEESND, D_SW_BLITZ1SEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_BLITZFIRESND,

    {{D_ATKPISTOLSND, D_SW_ATKPISTOLSND, MUSE_ACTORFIRESND,        },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_BLITZSTEALSND,

    {{D_BLITZSTEALSND, D_SW_BLITZSTEALSND, MUSE_GETPOWERDOWNSND,  },  0,SD_PRIOASNEAK, 0, 0, 0},

//SD_BLITZOUCHSND,

    {{D_BLITZOUCHSND, D_SW_BLITZOUCHSND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_BLITZDIESND,

    {{D_BLITZDIESND, D_SW_BLITZDIESND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_BLITZPLEADSND,

    {{D_BLITZPLEADSND, D_SW_BLITZPLEADSND, MUSE_LASTSOUND,        },  SD_PLAYONCE,SD_PRIOAGREET, 0, 0, 0},

//SD_BLITZPLEAD1SND,

    {{D_BLITZPLEAD1SND, D_SW_BLITZPLEAD1SND, MUSE_LASTSOUND,       },  SD_PLAYONCE,SD_PRIOAGREET, 0, 0, 0},

//SD_BLITZPLEAD2SND,

    {{D_BLITZPLEAD2SND, D_SW_BLITZPLEAD2SND, MUSE_LASTSOUND,       },  SD_PLAYONCE,SD_PRIOAGREET, 0, 0, 0},

//SD_ENFORCERSEESND,

    {{D_ENFORCERSEESND, D_SW_ENFORCERSEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_ENFORCERFIRESND,

    {{D_ENFORCERFIRESND, D_SW_ENFORCERFIRESND, MUSE_ACTORFIRESND,     },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_ENFORCERTHROWSND,

    {{D_ENFORCERTHROWSND, D_SW_ENFORCERTHROWSND, MUSE_ACTORTHROWSND,    },  0,SD_PRIOASNEAK, 0, 0, 0},

//SD_ENFORCEROUCHSND,

    {{D_ENFORCEROUCHSND, D_SW_ENFORCEROUCHSND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_ENFORCERDIESND,

    {{D_ENFORCERDIESND, D_SW_ENFORCERDIESND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_MONKSEESND,

    {{D_MONKSEESND, D_LASTSOUND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_MONKGRABSND,

    {{D_MONKGRABSND, D_LASTSOUND, MUSE_ACTORDOITSND,     },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_MONKOUCHSND,

    {{D_MONKOUCHSND, D_LASTSOUND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_MONKDIESND,

    {{D_MONKDIESND, D_LASTSOUND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_FIREMONKSEESND,

    {{D_FIREMONKSEESND, D_LASTSOUND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_FIREMONKFIRESND,

    {{D_FIREMONKFIRESND, D_LASTSOUND, MUSE_ACTORFIRESND,     },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_FIREMONKOUCHSND,

    {{D_FIREMONKOUCHSND, D_LASTSOUND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_FIREMONKDIESND,

    {{D_FIREMONKDIESND, D_LASTSOUND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_ROBOTSEESND,

    {{D_ROBOTSEESND, D_SW_ROBOTSEESND, MUSE_ACTORSEESND,      },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_ROBOTFIRESND,

    {{D_ROBOTFIRESND, D_SW_ROBOTFIRESND, MUSE_ACTORFIRESND,     },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_ROBOTDIESND,

    {{D_ROBOTDIESND, D_SW_ROBOTDIESND, MUSE_ACTORDIESND,      },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_ROBOTMOVESND,

    {{D_KRISTMOTORSND, D_SW_KRISTMOTORSND, MUSE_LASTSOUND,        },  SD_PLAYONCE,SD_PRIOENVRON, 0, 0, 0},

//SD_BALLISTIKRAFTSEESND,

    {{D_BAZOOKAFIRESND, D_SW_BAZOOKAFIRESND, MUSE_ACTORSEESND,   },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_BALLISTIKRAFTFIRESND,

    {{D_ROBOTFIRESND, D_SW_ROBOTFIRESND, MUSE_ACTORFIRESND,     },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_DARIANSEESND,

    {{D_DARIANSEESND, D_LASTSOUND, MUSE_BOSSSEESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANFIRESND,

    {{D_BAZOOKAFIRESND, D_SW_BAZOOKAFIRESND, MUSE_BOSSFIRESND,     },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANGONNAUSESND,

    {{D_DARIANGONNAUSESND, D_LASTSOUND, MUSE_BOSSDOSND,        },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANUSESND,

    {{D_TOUCHPLATESND, D_SW_TOUCHPLATESND, MUSE_BOSSDOSND,        },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANHIDESND,

    {{D_DARIANHIDESND, D_LASTSOUND, MUSE_BOSSDOSND,        },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANDIESND,

    {{D_DARIANDIESND, D_LASTSOUND, MUSE_BOSSDIESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANSAY1,

    {{D_DARIANSAY1, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANSAY2,

    {{D_DARIANSAY2, D_LASTSOUND, MUSE_BOSSHEYSND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARIANSAY3,

    {{D_DARIANSAY3, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTSEESND,

    {{D_KRISTSEESND, D_LASTSOUND, MUSE_BOSSSEESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTFIRESND,

    {{D_BAZOOKAFIRESND, D_SW_BAZOOKAFIRESND, MUSE_BOSSFIRESND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTMOTORSND,

    {{D_KRISTMOTORSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTTURNSND,

    {{D_KRISTTURNSND, D_LASTSOUND, MUSE_BOSSBEEPSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTDROPSND,

    {{D_KRISTDROPSND, D_LASTSOUND, MUSE_BOSSDOSND,        },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTMINEBEEPSND,

    {{D_KRISTMINEBEEPSND, D_LASTSOUND, MUSE_BOSSBEEPSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTMINEHITSND,

    {{D_KRISTMINEHITSND, D_LASTSOUND, MUSE_MISSILEHITSND,    },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTDIESND,

    {{D_KRISTDIESND, D_LASTSOUND, MUSE_BOSSDIESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTSAY1,

    {{D_KRISTSAY1, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTSAY2,

    {{D_KRISTSAY2, D_LASTSOUND, MUSE_BOSSHEYSND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_KRISTSAY3,

    {{D_KRISTSAY3, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_NMESEESND,

    {{D_NMESEESND, D_LASTSOUND, MUSE_BOSSSEESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_NMEREADYSND,

    {{D_NMEREADYSND, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_NMEFIRE1SND,

    {{D_BAZOOKAFIRESND, D_SW_BAZOOKAFIRESND, MUSE_BOSSFIRESND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_NMEAPARTSND,

    {{D_NMEAPARTSND, D_LASTSOUND, MUSE_BOSSBEEPSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_NMEUFOSND,

    {{D_NMEUFOSND, D_LASTSOUND, MUSE_MISSILEFIRESND,   },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_NMEDIESND,

    {{D_EXPLODESND, D_SW_EXPLODESND, MUSE_BOSSDIESND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKSEESND,

    {{D_DARKMONKSEESND, D_LASTSOUND, MUSE_BOSSSEESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKFIRE1SND,

    {{D_DARKMONKFIRE1SND, D_LASTSOUND, MUSE_BOSSFIRESND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKFIRE2SND,

    {{D_DARKMONKFIRE2SND, D_LASTSOUND, MUSE_BOSSFIRE2SND,     },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKFIRE3SND,

    {{D_DARKMONKFIRE3SND, D_LASTSOUND, MUSE_BOSSFIRESND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKFIRE4SND,

    {{D_DARKMONKFIRE4SND, D_LASTSOUND, MUSE_BOSSFIRE2SND,     },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKRECHARGESND,

    {{D_DARKMONKRECHARGESND, D_LASTSOUND, MUSE_WEAPONBUILDSND, },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKFLOATSND,

    {{D_DARKMONKFLOATSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKDIESND,

    {{D_DARKMONKDIESND, D_LASTSOUND, MUSE_BOSSDIESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKSAY1,

    {{D_DARKMONKSAY1, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKSAY2,

    {{D_DARKMONKSAY2, D_LASTSOUND, MUSE_BOSSHEYSND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_DARKMONKSAY3,

    {{D_DARKMONKSAY3, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKESEESND,

    {{D_SNAKESEESND, D_LASTSOUND, MUSE_BOSSSEESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKEREADYSND,

    {{D_SNAKEREADYSND, D_LASTSOUND, MUSE_BOSSBEEPSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKECHARGESND,

    {{D_SNAKECHARGESND, D_LASTSOUND, MUSE_WEAPONBUILDSND,   },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKEOUCHSND,

    {{D_SNAKEOUCHSND, D_LASTSOUND, MUSE_BOSSOUCHSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKEDIESND,

    {{D_SNAKEDIESND, D_LASTSOUND, MUSE_BOSSDIESND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKESPITSND,

    {{D_SNAKESPITSND, D_LASTSOUND, MUSE_BOSSFIRESND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKESAY1,

    {{D_SNAKESAY1, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKESAY2,

    {{D_SNAKESAY2, D_LASTSOUND, MUSE_BOSSHEYSND,       },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_SNAKESAY3,

    {{D_SNAKESAY3, D_LASTSOUND, MUSE_BOSSWARNSND,      },  0,SD_PRIOBOSS, 0, 0, 0},

//SD_EMPLACEMENTSEESND,

    {{D_EMPLACEMENTSEESND, D_LASTSOUND, MUSE_SWITCHSND,        },  0,SD_PRIOAGREET, 0, 0, 0},

//SD_EMPLACEMENTFIRESND,

    {{D_EMPLACEMENTFIRESND, D_LASTSOUND, MUSE_EMPFIRESND,       },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_BIGEMPLACEFIRESND,

    {{D_BIGEMPLACEFIRESND, D_LASTSOUND, MUSE_EMPFIRESND,       },  0,SD_PRIOAFIRE, 0, 0, 0},

//SD_OPENDOORSND,

    {{D_OPENDOORSND, D_SW_OPENDOORSND, MUSE_OPENDOORSND,       },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_CLOSEDOORSND,

    {{D_CLOSEDOORSND, D_SW_CLOSEDOORSND, MUSE_CLOSEDOORSND,      },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_DOORHITSND,

    {{D_ELEVATORENDSND, D_SW_ELEVATORENDSND, MUSE_LASTSOUND,           },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_FIRECHUTESND,

    {{D_FIRECHUTESND, D_SW_FIRECHUTESND, MUSE_MISSILEFIRESND,   },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_FIREBALLSND,

    {{D_FIREBALLSND, D_SW_FIREBALLSND, MUSE_LASTSOUND,        },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_FIREBALLHITSND,

    {{D_FIREBALLHITSND, D_SW_FIREBALLHITSND, MUSE_MISSILEHITSND,    },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_BLADESPINSND,

    {{D_BLADESPINSND, D_SW_BLADESPINSND, MUSE_SPINBLADESND,     },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_PUSHWALLSND,

    {{D_PUSHWALLSND, D_SW_PUSHWALLSND, MUSE_PUSHWALLSND,      },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_PUSHWALLHITSND,

    {{D_PUSHWALLHITSND, D_SW_PUSHWALLHITSND, MUSE_MISSILEHITSND,    },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_GOWALLSND,

    {{D_GOWALLSND, D_SW_GOWALLSND, MUSE_PUSHWALLSND,      },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_TURBOWALLSND,

    {{D_TURBOWALLSND, D_SW_TURBOWALLSND, MUSE_PUSHWALLSND,      },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_BOULDERHITSND,

    {{D_BOULDERHITSND, D_LASTSOUND, MUSE_MISSILEHITSND,    },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_BOULDERROLLSND,

    {{D_BOULDERROLLSND, D_LASTSOUND, MUSE_BOULDERSND,       },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_BOULDERFALLSND,

    {{D_BOULDERHITSND, D_LASTSOUND, MUSE_PITTRAPSND,       },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_PITTRAPSND,

    {{D_PITTRAPSND, D_SW_PITTRAPSND, MUSE_PITTRAPSND,       },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_FIREJETSND,

    {{D_FIREJETSND, D_SW_FIREJETSND, MUSE_FIREJETSND,       },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_ACTORSQUISHSND,

    {{D_ACTORSQUISHSND, D_SW_ACTORSQUISHSND, MUSE_ACTORSQUISHSND,   },  0,SD_PRIOADEATH, 0, 0, 0},

//SD_ACTORBURNEDSND,

    {{D_ACTORBURNEDSND, D_SW_ACTORBURNEDSND, MUSE_ACTOROUCHSND,     },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_ACTORSKELETONSND,

    {{D_ACTORSKELETONSND, D_SW_ACTORSKELETONSND, MUSE_LASTSOUND,        },  0,SD_PRIOAHURT, 0, 0, 0},

//SD_SPEARSTABSND,

    {{D_SPEARSTABSND, D_SW_SPEARSTABSND, MUSE_STABBERSND,       },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_CYLINDERMOVESND,

    {{D_CYLINDERMOVESND, D_SW_CYLINDERMOVESND, MUSE_CYLINDERHITSND,   },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_ELEVATORONSND,

    {{D_ELEVATORONSND, D_SW_ELEVATORONSND, MUSE_ELEVATORSND,      },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_ELEVATORENDSND,

    {{D_ELEVATORENDSND, D_SW_ELEVATORENDSND, MUSE_LASTSOUND,        },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_SPRINGBOARDSND,

    {{D_SPRINGBOARDSND, D_SW_SPRINGBOARDSND, MUSE_SPRINGBOARDSND,   },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_LIGHTNINGSND,

    {{D_LIGHTNINGSND, D_SW_LIGHTNINGSND, MUSE_LASTSOUND,        },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_WINDSND,

    {{D_WINDSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_WATERSND,

    {{D_LASTSOUND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOPCAUSD, 0, 0, 0},

//SD_BODYLANDSND,

    {{D_BODYLANDSND, D_SW_BODYLANDSND, MUSE_LASTSOUND,        },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_GIBSPLASHSND,

    {{D_GIBSPLASHSND, D_SW_GIBSPLASHSND, MUSE_LASTSOUND,       },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_ACTORLANDSND,

    {{D_ACTORLANDSND, D_SW_ACTORLANDSND, MUSE_LASTSOUND,       },  0,SD_PRIOENVRON, 0, 0, 0},

//SD_DOPEFISHSND,

    {{D_DOPEFISHSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_YOUSUCKSND,

    {{D_YOUSUCKSND, D_SW_YOUSUCKSND, MUSE_LASTSOUND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_SILLYMOVESND,

    {{D_SILLYMOVESND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_SOUNDSELECTSND,

    {{D_SOUNDSELECTSND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_SOUNDESCSND,

    {{D_SOUNDESCSND, D_SW_YOUSUCKSND, MUSE_LASTSOUND,        },  0,SD_PRIOSECRET, 0, 0, 0},

//SD_REMOTEM1SND,

    {{D_REMOTEM1SND, D_REMOTEM1SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM2SND,

    {{D_REMOTEM2SND, D_REMOTEM2SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM3SND,

    {{D_REMOTEM3SND, D_REMOTEM3SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM4SND,

    {{D_REMOTEM4SND, D_REMOTEM4SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM5SND,

    {{D_REMOTEM5SND, D_REMOTEM5SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM6SND,

    {{D_REMOTEM6SND, D_REMOTEM6SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM7SND,

    {{D_REMOTEM7SND, D_REMOTEM7SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM8SND,

    {{D_REMOTEM8SND, D_REMOTEM8SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM9SND,

    {{D_REMOTEM9SND, D_REMOTEM9SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_REMOTEM10SND,

    {{D_REMOTEM10SND, D_REMOTEM10SND, MUSE_LASTSOUND,        },  0,SD_PRIOREMOTE, 0, 0, 0},

//SD_LASTSOUND

    {{D_LASTSOUND, D_LASTSOUND, MUSE_LASTSOUND,        },  0,SD_PRIOSECRET, 0, 0, 0}
};

